name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t architecture-hexagonal-starter .
          docker tag architecture-hexagonal-starter ${{ secrets.DOCKER_USERNAME }}/architecture-hexagonal-starter:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/architecture-hexagonal-starter:develop

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
